apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "approval.name" . }}
spec:
  replicas: {{ .Values.approvalService.replicas }}
  selector:
    matchLabels:
      app: {{ include "approval.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "approval.name" . }}
    spec:
      serviceAccountName: {{ include "approval.name" . }}
      nodeSelector:
        {{- toYaml .Values.approvalService.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.approvalService.tolerations | nindent 8 }}
        
      volumes:
      - name: secrets-store-inline
        secret:
          secretName: {{ .Values.approvalService.config.secrets.name }}

      {{ if .Values.approvalService.volumes }}
      {{ toYaml .Values.approvalService.volumes | nindent 6 }}
      {{ end }}

      containers:
      - name: controller
        image: {{ .Values.approvalService.image }}
        env:
        - name: NAMESPACE
          value: {{ .Release.Namespace }}

        - name: KEYVAULT_SECRETS_MNT_PATH
          value: {{ .Values.approvalService.config.secretsMountPath }}

        - name: METADATA_CONTAINER_NAME
          value: {{ include "metadata.name" . }}

        - name: PUBLISH_CONTAINER_NAME
          value: {{ include "publish.name" . }}

        {{ if .Values.approvalService.env }}
        {{ toYaml .Values.approvalService.env | nindent 8 }}
        {{ end }}
        
        volumeMounts:

        - name: secrets-store-inline
          mountPath: {{ .Values.approvalService.config.secrets.mountPath }}
          readOnly: true

        {{ if .Values.approvalService.volumeMounts }}
        {{ toYaml .Values.approvalService.volumeMounts | nindent 8 }}
        {{ end }}
          
        resources:
          {{- toYaml .Values.approvalService.resources | nindent 10 }}