apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${cr8tor_publisher_namespace}
configMapGenerator:
  - name: cr8tor-helm-config
    files:
      - values.yaml=values.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
- ../shared