approvalService:
  image: "${cr8tor_approval_service_image}"
metadataService:
  image: "${cr8tor_metadata_service_image}"
publishService:
  image: "${cr8tor_publish_service_image}"

storage:
  lsc:
    pvcs:
      staging:
        name: lsc-staging-local
        storageClassName: cr8tor-publisher-default
        accessModes:
        - ReadWriteOnce
      production:
        name: lsc-prod-local
        storageClassName: cr8tor-publisher-default
        accessModes:
        - ReadWriteOnce
  nw:
    pvcs:
      staging:
        name: nw-staging-local
        storageClassName: cr8tor-publisher-default
        accessModes:
        - ReadWriteOnce

      production:
        name: nw-prod-local
        storageClassName: cr8tor-publisher-default
        accessModes:
        - ReadWriteOnce

    
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect : "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect : "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 64m
  className: nginx
  host: cr8tor.xlscsde.local
  tls:
    secretName: cr8tor.xlscsde.local-tls