apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: {{ include "metadata.name" . }}
  name: {{ include "metadata.name" . }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: None
  selector:
    app: {{ include "metadata.name" . }}
  ports:
  - name: http
    port: 8002
    targetPort: 8002