apiVersion: xlscsde.nhs.uk/v1
kind: SecretsDistribution
metadata:
  name: ${dns_prefix}cr8tor.${private_dnz_zone}-tls
  annotations:
    xlscsde.nhs.uk/secretUsage: "Wildcard Certificate"
spec:
  name: ${dns_prefix}cr8tor.${private_dnz_zone}-tls
  type: kubernetes.io/tls
  secrets:
  - from: WildcardCertificate
    to: tls.crt

  - from: WildcardCertificateKey
    to: tls.key