apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cr8tor
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    userAssignedIdentityID: ${azure_client_id}
    keyvaultName: "kv-lsc-uks-datadev-cr8" #${cr8tor_keyvault_name}
    tenantId: "f12f0279-8a84-4068-8322-7a6fb0f839b8" # "${cr8tor_tenant_id}"
    useVMManagedIdentity: "true"                        # Set to true for using managed identity
    objects:  |
      array:
        - |
          objectName: approvalserviceapikey
          objectType: secret
        - |
          objectName: metadataserviceapikey
          objectType: secret
        - |
          objectName: publishserviceapikey
          objectType: secret
        - |
          objectName: databricksspnclientid
          objectType: secret
        - |
          objectName: databricksspnsecret
          objectType: secret