apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cr8tor-lsc-staging
provisioner: file.csi.azure.com
parameters:
  skuName: Standard_ZRS
  location: ${azure_location}
  storageAccount: ${azure_storage_account}
  secretNamespace: ${cr8tor_publisher_namespace}
  server: ${azure_storage_account}.privatelink.file.core.windows.net
  resourceGroup: ${azure_resource_group}
  storeAccountKey: "true"
  shareName: cr8tor-lsc-staging
  secretName: cr8tor-lsc-staging-int
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=999
  - gid=999
  - mfsymlinks # Enable support for Minshall+French symlinks 
  - cache=strict # https://linux.die.net/man/8/mount.cifs
  - actimeo=30 # reduce latency for metadata-heavy workload
  - nosharesock # reduce probability of reconnect race
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cr8tor-lsc-prod
provisioner: file.csi.azure.com
parameters:
  skuName: Standard_ZRS
  location: ${azure_location}
  storageAccount: ${azure_storage_account}
  secretNamespace: ${cr8tor_publisher_namespace}
  server: ${azure_storage_account}.privatelink.file.core.windows.net
  resourceGroup: ${azure_resource_group}
  storeAccountKey: "true"
  shareName: cr8tor-lsc-prod
  secretName: cr8tor-lsc-prod-int
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=999
  - gid=999
  - mfsymlinks # Enable support for Minshall+French symlinks 
  - cache=strict # https://linux.die.net/man/8/mount.cifs
  - actimeo=30 # reduce latency for metadata-heavy workload
  - nosharesock # reduce probability of reconnect race
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cr8tor-nw-staging
provisioner: file.csi.azure.com
parameters:
  skuName: Standard_ZRS
  location: ${azure_location}
  storageAccount: ${azure_storage_account}
  secretNamespace: ${cr8tor_publisher_namespace}
  server: ${azure_storage_account}.privatelink.file.core.windows.net
  resourceGroup: ${azure_resource_group}
  storeAccountKey: "true"
  shareName: cr8tor-nw-staging
  secretName: cr8tor-nw-staging-int
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=999
  - gid=999
  - mfsymlinks # Enable support for Minshall+French symlinks 
  - cache=strict # https://linux.die.net/man/8/mount.cifs
  - actimeo=30 # reduce latency for metadata-heavy workload
  - nosharesock # reduce probability of reconnect race
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cr8tor-nw-prod
provisioner: file.csi.azure.com
parameters:
  skuName: Standard_ZRS
  location: ${azure_location}
  storageAccount: ${azure_storage_account}
  secretNamespace: ${cr8tor_publisher_namespace}
  server: ${azure_storage_account}.privatelink.file.core.windows.net
  resourceGroup: ${azure_resource_group}
  storeAccountKey: "true"
  shareName: cr8tor-nw-prod
  secretName: cr8tor-nw-prod-int
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=999
  - gid=999
  - mfsymlinks # Enable support for Minshall+French symlinks 
  - cache=strict # https://linux.die.net/man/8/mount.cifs
  - actimeo=30 # reduce latency for metadata-heavy workload
  - nosharesock # reduce probability of reconnect race
---
