approvalService:
  config:
    secrets:
      mountPath: /home/appuser/secrets
  replicas: 1
  image: lscsde/cr8tor-approval-service:latest
  nodeSelector: {}
  tolerations: []
  volumes: 
  - name: secrets-store-inline
    secret:
      secretName: approval-service

  volumeMounts: []
  env: 
    - name: APP_NAME
      value: "CR8TOR - Approval Service API"
    - name: ENVIRONMENT
      value: "kubernetes"
  resources: {}

metadataService:
  config:
    secrets:
      mountPath: /home/appuser/secrets
  replicas: 1
  image: lscsde/cr8tor-metadata-service:latest
  nodeSelector: {}
  tolerations: []
  volumes: 
  - name: secrets-store-inline
    secret:
      secretName: metadata-service
  volumeMounts: []
  env: 
    - name: APP_NAME
      value: "CR8TOR - Metadata Service API"
    - name: ENVIRONMENT
      value: "kubernetes"
  resources: {}

publishService:
  config:
    secrets:
      mountPath: /home/appuser/secrets
      
  replicas: 1
  image: lscsde/cr8tor-publish-service:latest
  nodeSelector: {}
  tolerations: []
  volumes: 
  - name: secrets-store-inline
    secret:
      secretName: publish-service
  volumeMounts: []
  env: 
    - name: DESTINATION_POSTGRESQL_HOST
      value: "datashield-postgres-cluster-rw.datashield.svc.cluster.local"
    - name: DESTINATION_POSTGRESQL_DATABASE
      value: "opal-resource-db"
    - name: DESTINATION_POSTGRESQL_USERNAME
      valueFrom:
        secretKeyRef:
          name: opal-resource-db-secret
          key: username
    - name: DESTINATION_POSTGRESQL_PASSWORD_SECRET_NAME
      valueFrom:
        secretKeyRef:
          name: opal-resource-db-secret
          key: password
    - name: DESTINATION_POSTGRESQL_PORT
      value: "5432"
    - name: DESTINATION_POSTGRESQL_OPAL_READONLY_USERNAME
      valueFrom:
        secretKeyRef:
          name: opal-resource-db-secret
          key: username
    - name: DESTINATION_POSTGRESQL_OPAL_READONLY_PASSWORD_SECRET_NAME
      valueFrom:
        secretKeyRef:
          name: opal-resource-db-secret
          key: password
    - name: DESTINATION_OPAL_HOST
      value: "http://host.docker.internal:8880"
    - name: DESTINATION_OPAL_USERNAME
      value: "administrator"
    - name: DESTINATION_OPAL_PASSWORD_SECRET_NAME
      valueFrom:
        secretKeyRef:
          name: datashield-secrets
          key: opal-administrator-password
  resources: {}

service:
  type: ClusterIP

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect : "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect : "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 64m
    xlscsde.nhs.uk/dns-record: cr8tor
  className: nginx
  host: dev-cr8tor.xlscsde.nhs.uk
  tls:
    secretName: dev-cr8tor.xlscsde.nhs.uk-tls

storage: 
  lsc:
    env: TARGET_STORAGE_ACCOUNT_LSC_SDE_MNT_PATH
    mountPath: /home/appuser/outputs/lsc
    pvcs:
      staging:
        name: lsc-staging
        create: true
        storageClassName: cr8tor-lsc-staging
        accessModes:
        - ReadWriteMany

      production:
        name: lsc-prod
        create: true
        storageClassName: cr8tor-lsc-prod
        accessModes:
        - ReadWriteMany
  nw:
    env: TARGET_STORAGE_ACCOUNT_NW_SDE_MNT_PATH
    mountPath: /home/appuser/outputs/nw
    pvcs:
      staging:
        name: nw-staging
        create: true
        storageClassName: cr8tor-nw-staging
        accessModes:
        - ReadWriteMany

      production:
        name: nw-prod
        create: true
        storageClassName: cr8tor-nw-prod
        accessModes:
        - ReadWriteMany

    