name: Test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, ready_for_review]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.5.16"

      - name: Test Publish Service
        working-directory: publish-service
        run: |
                uv run pytest

      - name: Test Metadata Service
        working-directory: metadata-service
        run: |
                uv run pytest

      - name: Test Approval Service
        working-directory: approval-service
        run: |
                uv run pytest